### ISSUE TITLE
Which ones are the correct labels in labelled test data?

### ISSUE THREAD

**Issue by reklanirs** [kj2013/claff-offmychest#2]
Hi, in the labelled test data you just uploaded, I saw two sets of labels:

"SharedTask_Emotional_disclosure,SharedTask_Information_disclosure,SharedTask_Emo_support,SharedTask_Info_support"

and

"Emotional_disclosure,Information_disclosure,Emo_support,Info_support"

And the values are not equal between the corresponding labels.

Which set is the correct label?

**Comment by kokiljaidka** [comment]
Hi, the 2020 Shared Task system runs were evaluated using the first four columns (the ones starting with "SharedTask_*"), but we’ve since identified and corrected a lot of labeling errors. For future research, we would recommend using the new labels.
